### ISSUE TITLE
Opam release

### ISSUE THREAD

**Issue by christophe-riolo** [anmonteiro/piaf#117]
Hello,

I am reviving an old project of mine that depends on Piaf, from back when it was not published on Opam yet, and now that i check my dependencies I see that Piaf has been actively developed in the mean time, but that there has bee no release in a year. So, I was wondering is there is a plan for a release ?

Thanks for the great software!

**Comment by anmonteiro** [comment]
I can make a release soon-ish but it might be a little harder after #114.

**Comment by christophe-riolo** [comment]
Thanks for the information :pray:

**Comment by anmonteiro** [comment]
you can pin this library via opam now, after #167
