### ISSUE TITLE
Opam install issue

### ISSUE THREAD

**Issue by FreerGit** [anmonteiro/piaf#140]
Not sure if I should post here or in opam repo but here goes.

I've been trying to install piaf through opam but just keep running into errors, every library so far works fine. I have tried with ocaml version 5.0.0~alpha0 and 1, 5.0.0+trunk and also 4.14.0, none of them seem to be able to compile the package correctly?
![image](https://user-images.githubusercontent.com/42868792/193917936-e795eb48-1fef-41f0-9a16-f6941dea1395.png)

I also tried to install through the websocket branch but same issue, I also tried to simply git clone the repo and build it and got build errors too. 

Im very new to ocaml, opam and dune so im probably doing something wrong. After cloning and running "opam install ." (opam verison 2.1) I got this:

![image](https://user-images.githubusercontent.com/42868792/193919742-88b39534-f029-4b2c-9593-6abfd62132eb.png)

**Comment by anmonteiro** [comment]
I don't use OPAM and I have no idea how to make it work there, given the lack of support for transitively depending on forks.

**Comment by anmonteiro** [comment]
#167 added a way to pin this library locally using opam
