### ISSUE TITLE
Memory leak with Eio Piaf Server

### ISSUE THREAD

**Issue by fraidev** [anmonteiro/piaf#147]
## Problem

I have memory leaks with a Piaf Server as a Proxy. 
I already reproduced it on prod with a Linux x86 and locally with a macOS ARM64.
I suspect that this problem is related only to the Piaf Serve.

## How to reproduce

With the new example in PR https://github.com/anmonteiro/piaf/pull/146. 

Execute to run the server:
```
dune exec examples/eio/eio_server_get.exe                                                                                                                           
```

Stress it with some client HTTP tool, for example [hey](https://github.com/rakyll/hey).

```
hey -n 50000 http://localhost:8080/
```

Follow the memory with a tool like htop. 
Before:
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/25258368/198910942-3b6edd35-0cd9-468b-9440-12affab8c4f8.png">

After:
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/25258368/198911009-ab74c389-932d-42d1-a246-41d454eee106.png">

The memory only increases after each request, it seems that there is no GC.

**Comment by anmonteiro** [comment]
I believe this has been fixed with a few separate improvements. Feel free to open if that's not the case.
