### ISSUE TITLE
Allow to pass cacert in client config as pem string

### ISSUE THREAD

**Issue by Firgeis** [anmonteiro/piaf#91]
Right now to pass a certificate to you must provide a file path for the library to parse:

`cacert : string option (** The path to a CA certificates file in PEM format *)`

If I had the certificate already parsed I would need to write a file. It would be great if I could pass the string of the certificate as a config

**Comment by anmonteiro** [comment]
I think this could be achieved by calling [`use_certificate_from_string`](https://github.com/savonet/ocaml-ssl/blob/master/src/ssl.mli#L249) in the openssl module. Do you wanna give it a shot?
